### ISSUE TITLE
Difference inquiry

### ISSUE THREAD

**Issue by je-santos** [xl402/performer#7]
Dear authors,

Thanks for you code. It's a really nice, minimal implementation.
I was wondering, what are the main  differences with the code on the official google repo?

Thanks in advance.

Best,
Javier

**Comment by xl402** [comment]
Hi Javier,

Thanks for your message and feedback.

To our best knowledge, we did not change the core implementation (in fact, tests were designed by looking at Google's original implementation).

We did, however, omit the naive method to approximate the softmax kernel (the paper calls it SM_m trig) as it is not practical.

Best,

Tom

**Comment by je-santos** [comment]
Great! Thanks again.
Are you guys planning to add a license to your repo?

Best regards,
Javier

**Comment by xl402** [comment]
Just added :)

**Comment by je-santos** [comment]
Thanks a lot!!! 😊
