### ISSUE TITLE
how to use this on Colab?

### ISSUE THREAD

**Issue by rebeen** [xl402/performer#8]
could you please let me know how to use this on google colab?

Thank you

**Comment by xl402** [comment]
Np! In ur notebook, the first cell should clone:

`!git clone https://github.com/xl402/performer.git`

The second cell adds the repo to path:

```
import sys
sys.path.insert(1, "performer")
```

**Comment by rebeen** [comment]
Thank you very much, for your quick replay, I actually copied all the code and worked without any problem except, I changed GOR to  GaussianOrthogonalRandomMatrix
sorry, can I use this with my code for temporal data?  
for example can I use your code instead of the below self attention(it is just called )

    x = Conv1D(256, 3, activation='elu')(x)
    x = LayerNormalization()(x)
    x = Dropout(0.2)(x)
    print(x.shape)
    x = Dense(192, activation='elu')(x)
    x = LayerNormalization()(x)
    x = Dropout(0.2)(x)

    print("comes, x - ", x.shape)

    if True:
        x = Reshape([5 * 3, 64 * 3])(x)
        print(x.shape)
        att = MultiHeadsAttModel(l=5 * 3, d=64 * 3, dv=8 * 3, dout=192, nv=8)  # d must be equal to nv*dv
        x = att([x, x, x])
        print(x.shape)
        x = Reshape([15, 192])(x)
        # x = NormL()(x)
        print(x.shape)
        # x = BatchNormalization()(x)

**Comment by xl402** [comment]
I am not sure what you mean by "except, I changed GOR to GaussianOrthogonalRandomMatrix" or its relevance to the question. But in theory yes, the code is compatible with the existing self-attention.

**Comment by rebeen** [comment]
Yes I could adapt it  with my code, thank you  very much

everything is fine in your code

**Comment by xl402** [comment]
fantastic :)
